name: terraform flow

on:
  push:
    branches:
      - main  # or the branch you want to test

permissions:
  id-token: write       # Needed for OIDC
  contents: read

jobs:
  terraform-flow:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo (optional, but standard)
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0        

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::070593202443:role/git_role
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=env/dev init

      - name: Terraform Format Check
        run: terraform -chdir=env/dev fmt -check

      - name: Terraform Validate
        run: terraform -chdir=env/dev validate


      - name: Terraform Plan
        run: terraform -chdir=env/dev plan -out=tfplan

    #   - name: Upload Terraform Plan
    #     uses: actions/upload-artifact@v3
    #     with:
    #         name: tfplan
    #         path: env/dev/tfplan

      - name: Terraform Apply
        run: terraform -chdir=env/dev apply -auto-approve tfplan
